Fix Dockerfile
Missing shard.yml. Please run 'shards init'
The command '/bin/sh -c shards update' returned a non-zero code: 1
ERROR: Service 'relay' failed to build : Build failed